name: Build and test

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    types: [created]

env:
  default-php-version: '8.2'
  coverage-with: 'sqlite'

concurrency:
  group: Build ${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Run tests
    uses: monicahq/workflows/.github/workflows/laravel.yml@v2
    with:
      php-versions: "['8.2']"
      connections: "['sqlite', 'mysql', 'pgsql']"
      default-php-version: '8.2'
      default-connection: sqlite
      project: monicahq_customers
      database_name: customers
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
