name: Build and test

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    types: [created]

env:
  default-php-version: '8.2'
  coverage-with: 'sqlite'

concurrency:
  group: Build ${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    uses: monicahq/workflows/.github/workflows/laravel.yml@init
    with:
      php-version: ${{ matrix.php-version }}
      connection: ${{ matrix.connection }}
      coverage: ${{ matrix.connection == 'sqlite' && matrix.php-version == '8.2' }}

    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.2']
        connection: [sqlite, mysql, pgsql]

  reporting:
    uses: monicahq/workflows/.github/workflows/reporting.yml@init
    with:
      project: monicahq_version
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    needs: tests

  junit:
    uses: monicahq/workflows/.github/workflows/junit.yml@init
    needs: tests
