name: Static analysis

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: Static ${{ github.ref }}
  cancel-in-progress: true

jobs:
  statics:
    name: Static analysis
    uses: monicahq/workflows/.github/workflows/static.yml@main
    with:
      php-version: 8.2
